title = "AlenLiuの作品集"

languageCode = "en-us"
copyright = "© AlenLiu"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "en"
enableRobotsTXT = true
# timeZone = "Europe/Berlin"
theme = "gallery"

[params]
  title = "My Gallery"
  description = "AlenLiu's Gallery"
  defaultTheme = "dark"

[author]
  name = "AlenLiu"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"

# [menu]
# [[menu.footer]]
#   name = "GitHub"
#   url = "https://github.com/nicokaiser/hugo-theme-gallery/"
#   weight = 3
